language: node_js
node_js:
  - node
sudo: required
services:
  - docker
addons:
  sauce_connect:
    username: paperhive
  jwt:
    secure: "j81HTjQenXBJTorpThKgTB2Sg64U6GM3Ytp5Y5oUeBMZJItvootdkAZD9qzVGZ3RPyRVr5C917CwQmjyincr7S2hv8flfEXNyWz0if2P5HHXuh3q3FUG3S0srQ9PDKLOmFioyasWksrH2XMz5XbQ2kFhNezjRS1UM2FYLgSPwqY="

before_script:
  - cp config.json.default config.json
script:
  - npm run build
  - npm test
after_success:
  - export DOCKER_IMAGE_NAME="gcr.io/paperhive-c0ff33/frontend:${TRAVIS_COMMIT:0:8}"
  - docker build -t ${DOCKER_IMAGE_NAME} .
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install google-cloud-sdk
  - gcloud config set project paperhive-c0ff33
  - openssl aes-256-cbc -K $encrypted_90e3403db14e_key -iv $encrypted_90e3403db14e_iv -in gcloud-secret.json.enc -out gcloud-secret.json -d
  - gcloud auth activate-service-account --key-file gcloud-secret.json
  - gcloud docker -- push ${DOCKER_IMAGE_NAME}
