language: node_js
node_js:
  - node
sudo: required
services:
  - docker
before_script:
  - cp config.json.default config.json
script:
  - npm run build
after_success:
  - docker build -t gcr.io/paperhive-c0ff33/frontend:$TRAVIS_COMMIT .
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install google-cloud-sdk
  - gcloud config set project paperhive-c0ff33
  - openssl aes-256-cbc -K $encrypted_90e3403db14e_key -iv $encrypted_90e3403db14e_iv -in gcloud-secret.json.enc -out gcloud-secret.json -d
  - gcloud auth activate-service-account --key-file gcloud-secret.json
  - gcloud docker -- push gcr.io/paperhive-c0ff33/frontend:$TRAVIS_COMMIT
  #- npm test
# cache:
#   directories:
#     - node_modules
#     - bower_components
# env:
#   global:
#     - secure: htpFvFnIWQWt5OE/UempJalrnle2bP3mAv0ZTD/pi9pPWV8lgHcR9pINL6Pzu3udbMFPGiKVJR7iMxNrkhNR5Iw3o00O4DJZl238K1P4A6XRAF0itu2o7tQ+/8eT91oITwsoPj0xAtBIKlZ67nGk5efJGP89YGZTip1Jb7B0P6s=
#     - secure: kbgPNvbAPh7UyBFFMmRjFVn30Eq57MRNWdv4YmBYzGv04Fns7CHe6sscSWlOBvzjAhrht9XYBt56QMHe7b/dlimG0/UO+kyij1UYU1dYv54tynamnl0PEDkhuH/knewfFVFOy6KsVfw5FK7dTyGTD0YsL4wuiS91wYUo7l1uptw=

# addons:
#   sauce_connect: true
