apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: frontend-$PAPERHIVE_BRANCH-service
  labels:
    name: frontend
    branch: $PAPERHIVE_BRANCH
    commit: $PAPERHIVE_COMMIT
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    name: frontend
    branch: $PAPERHIVE_BRANCH
    commit: $PAPERHIVE_COMMIT
